language: dart

dart:
- dev
- 2.1.1

matrix:
  include:
  - dart: dev
    dart_task:
      - dartanalyzer
      - dartfmt
  - dart: dev
    dart_task:
      - test: -p vm
      - test: -p chrome
  - dart: 2.1.1
    dart_task:
      - test: -p vm
      - test: -p chrome

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
