name: clock
version: 1.0.1
description: A fakeable wrapper for dart:core clock APIs
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/clock

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '>=0.9.0 <2.0.0'

dev_dependencies:
  test: ^1.0.0
