name: clock
version: 1.1.0
description: A fakeable wrapper for dart:core clock APIs
homepage: https://github.com/dart-lang/clock

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
