name: clock
version: 1.1.0-nullsafety.2
description: A fakeable wrapper for dart:core clock APIs
homepage: https://github.com/dart-lang/clock

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
